//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LP2MegaAutos.ServicioOrdenTrabajo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.megaautos.com.pe/", ConfigurationName="ServicioOrdenTrabajo.OrdenTrabajoWS")]
    public interface OrdenTrabajoWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/OrdenTrabajoWS/eliminarOrdenTrabajoRequest", ReplyAction="http://services.megaautos.com.pe/OrdenTrabajoWS/eliminarOrdenTrabajoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoResponse eliminarOrdenTrabajo(LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/OrdenTrabajoWS/eliminarOrdenTrabajoRequest", ReplyAction="http://services.megaautos.com.pe/OrdenTrabajoWS/eliminarOrdenTrabajoResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoResponse> eliminarOrdenTrabajoAsync(LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/OrdenTrabajoWS/insertarOrdenTrabajoRequest", ReplyAction="http://services.megaautos.com.pe/OrdenTrabajoWS/insertarOrdenTrabajoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoResponse insertarOrdenTrabajo(LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/OrdenTrabajoWS/insertarOrdenTrabajoRequest", ReplyAction="http://services.megaautos.com.pe/OrdenTrabajoWS/insertarOrdenTrabajoResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoResponse> insertarOrdenTrabajoAsync(LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/OrdenTrabajoWS/actualizarOrdenTrabajoRequest", ReplyAction="http://services.megaautos.com.pe/OrdenTrabajoWS/actualizarOrdenTrabajoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoResponse actualizarOrdenTrabajo(LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/OrdenTrabajoWS/actualizarOrdenTrabajoRequest", ReplyAction="http://services.megaautos.com.pe/OrdenTrabajoWS/actualizarOrdenTrabajoResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoResponse> actualizarOrdenTrabajoAsync(LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/OrdenTrabajoWS/listarOrdenTrabajoRequest", ReplyAction="http://services.megaautos.com.pe/OrdenTrabajoWS/listarOrdenTrabajoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoResponse listarOrdenTrabajo(LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/OrdenTrabajoWS/listarOrdenTrabajoRequest", ReplyAction="http://services.megaautos.com.pe/OrdenTrabajoWS/listarOrdenTrabajoResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoResponse> listarOrdenTrabajoAsync(LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenTrabajo", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class eliminarOrdenTrabajoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idOT;
        
        public eliminarOrdenTrabajoRequest() {
        }
        
        public eliminarOrdenTrabajoRequest(int idOT) {
            this.idOT = idOT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenTrabajoResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class eliminarOrdenTrabajoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarOrdenTrabajoResponse() {
        }
        
        public eliminarOrdenTrabajoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class ordenTrabajo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private cliente clienteField;
        
        private double comprasRptoField;
        
        private comprobantePago comprobantePagoField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idField;
        
        private double margenBrutoField;
        
        private string numeroOrdenField;
        
        private double porcentajeField;
        
        private double salidasAlmacenField;
        
        private sede sedeField;
        
        private double serTerTallerField;
        
        private double servTercerosField;
        
        private servicio[] serviciosField;
        
        private string tipoSiniestroField;
        
        private double totalEgresosField;
        
        private double totalIngresosField;
        
        private vehiculo vehiculoField;
        
        private double mObraMecanicaField;
        
        private double mObraPinturaField;
        
        private double mObraPlanchadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double comprasRpto {
            get {
                return this.comprasRptoField;
            }
            set {
                this.comprasRptoField = value;
                this.RaisePropertyChanged("comprasRpto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public comprobantePago comprobantePago {
            get {
                return this.comprobantePagoField;
            }
            set {
                this.comprobantePagoField = value;
                this.RaisePropertyChanged("comprobantePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double margenBruto {
            get {
                return this.margenBrutoField;
            }
            set {
                this.margenBrutoField = value;
                this.RaisePropertyChanged("margenBruto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string numeroOrden {
            get {
                return this.numeroOrdenField;
            }
            set {
                this.numeroOrdenField = value;
                this.RaisePropertyChanged("numeroOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double porcentaje {
            get {
                return this.porcentajeField;
            }
            set {
                this.porcentajeField = value;
                this.RaisePropertyChanged("porcentaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double salidasAlmacen {
            get {
                return this.salidasAlmacenField;
            }
            set {
                this.salidasAlmacenField = value;
                this.RaisePropertyChanged("salidasAlmacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public sede sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double serTerTaller {
            get {
                return this.serTerTallerField;
            }
            set {
                this.serTerTallerField = value;
                this.RaisePropertyChanged("serTerTaller");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public double servTerceros {
            get {
                return this.servTercerosField;
            }
            set {
                this.servTercerosField = value;
                this.RaisePropertyChanged("servTerceros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("servicios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public servicio[] servicios {
            get {
                return this.serviciosField;
            }
            set {
                this.serviciosField = value;
                this.RaisePropertyChanged("servicios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string tipoSiniestro {
            get {
                return this.tipoSiniestroField;
            }
            set {
                this.tipoSiniestroField = value;
                this.RaisePropertyChanged("tipoSiniestro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public double totalEgresos {
            get {
                return this.totalEgresosField;
            }
            set {
                this.totalEgresosField = value;
                this.RaisePropertyChanged("totalEgresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public double totalIngresos {
            get {
                return this.totalIngresosField;
            }
            set {
                this.totalIngresosField = value;
                this.RaisePropertyChanged("totalIngresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public vehiculo vehiculo {
            get {
                return this.vehiculoField;
            }
            set {
                this.vehiculoField = value;
                this.RaisePropertyChanged("vehiculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public double mObraMecanica {
            get {
                return this.mObraMecanicaField;
            }
            set {
                this.mObraMecanicaField = value;
                this.RaisePropertyChanged("mObraMecanica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public double mObraPintura {
            get {
                return this.mObraPinturaField;
            }
            set {
                this.mObraPinturaField = value;
                this.RaisePropertyChanged("mObraPintura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public double mObraPlanchado {
            get {
                return this.mObraPlanchadoField;
            }
            set {
                this.mObraPlanchadoField = value;
                this.RaisePropertyChanged("mObraPlanchado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoField;
        
        private int idField;
        
        private string nombreField;
        
        private string numDocumentoField;
        
        private string telefonoField;
        
        private string tipoClienteField;
        
        private string tipoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string numDocumento {
            get {
                return this.numDocumentoField;
            }
            set {
                this.numDocumentoField = value;
                this.RaisePropertyChanged("numDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipoCliente {
            get {
                return this.tipoClienteField;
            }
            set {
                this.tipoClienteField = value;
                this.RaisePropertyChanged("tipoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class vehiculo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string placaField;
        
        private cliente propietarioField;
        
        private string tipoVehiculoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public cliente propietario {
            get {
                return this.propietarioField;
            }
            set {
                this.propietarioField = value;
                this.RaisePropertyChanged("propietario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoVehiculo {
            get {
                return this.tipoVehiculoField;
            }
            set {
                this.tipoVehiculoField = value;
                this.RaisePropertyChanged("tipoVehiculo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class servicio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoServicioField;
        
        private string descripcionField;
        
        private int idField;
        
        private string nombreField;
        
        private string tipoServicioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoServicio {
            get {
                return this.codigoServicioField;
            }
            set {
                this.codigoServicioField = value;
                this.RaisePropertyChanged("codigoServicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tipoServicio {
            get {
                return this.tipoServicioField;
            }
            set {
                this.tipoServicioField = value;
                this.RaisePropertyChanged("tipoServicio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class sede : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string direccionField;
        
        private string distritoField;
        
        private int idField;
        
        private string nombreField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class comprobantePago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idField;
        
        private double montoField;
        
        private string numeroComprobanteField;
        
        private ordenTrabajo ordenTrabajoField;
        
        private string tipoComprobanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string numeroComprobante {
            get {
                return this.numeroComprobanteField;
            }
            set {
                this.numeroComprobanteField = value;
                this.RaisePropertyChanged("numeroComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ordenTrabajo ordenTrabajo {
            get {
                return this.ordenTrabajoField;
            }
            set {
                this.ordenTrabajoField = value;
                this.RaisePropertyChanged("ordenTrabajo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
                this.RaisePropertyChanged("tipoComprobante");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOrdenTrabajo", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class insertarOrdenTrabajoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioOrdenTrabajo.ordenTrabajo objOT;
        
        public insertarOrdenTrabajoRequest() {
        }
        
        public insertarOrdenTrabajoRequest(LP2MegaAutos.ServicioOrdenTrabajo.ordenTrabajo objOT) {
            this.objOT = objOT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOrdenTrabajoResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class insertarOrdenTrabajoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarOrdenTrabajoResponse() {
        }
        
        public insertarOrdenTrabajoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarOrdenTrabajo", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class actualizarOrdenTrabajoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioOrdenTrabajo.ordenTrabajo objOT;
        
        public actualizarOrdenTrabajoRequest() {
        }
        
        public actualizarOrdenTrabajoRequest(LP2MegaAutos.ServicioOrdenTrabajo.ordenTrabajo objOT) {
            this.objOT = objOT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarOrdenTrabajoResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class actualizarOrdenTrabajoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarOrdenTrabajoResponse() {
        }
        
        public actualizarOrdenTrabajoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenTrabajo", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class listarOrdenTrabajoRequest {
        
        public listarOrdenTrabajoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenTrabajoResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class listarOrdenTrabajoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioOrdenTrabajo.ordenTrabajo[] @return;
        
        public listarOrdenTrabajoResponse() {
        }
        
        public listarOrdenTrabajoResponse(LP2MegaAutos.ServicioOrdenTrabajo.ordenTrabajo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdenTrabajoWSChannel : LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenTrabajoWSClient : System.ServiceModel.ClientBase<LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS>, LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS {
        
        public OrdenTrabajoWSClient() {
        }
        
        public OrdenTrabajoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenTrabajoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenTrabajoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoResponse LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS.eliminarOrdenTrabajo(LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoRequest request) {
            return base.Channel.eliminarOrdenTrabajo(request);
        }
        
        public int eliminarOrdenTrabajo(int idOT) {
            LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoRequest inValue = new LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoRequest();
            inValue.idOT = idOT;
            LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoResponse retVal = ((LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS)(this)).eliminarOrdenTrabajo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoResponse> LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS.eliminarOrdenTrabajoAsync(LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoRequest request) {
            return base.Channel.eliminarOrdenTrabajoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoResponse> eliminarOrdenTrabajoAsync(int idOT) {
            LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoRequest inValue = new LP2MegaAutos.ServicioOrdenTrabajo.eliminarOrdenTrabajoRequest();
            inValue.idOT = idOT;
            return ((LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS)(this)).eliminarOrdenTrabajoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoResponse LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS.insertarOrdenTrabajo(LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoRequest request) {
            return base.Channel.insertarOrdenTrabajo(request);
        }
        
        public int insertarOrdenTrabajo(LP2MegaAutos.ServicioOrdenTrabajo.ordenTrabajo objOT) {
            LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoRequest inValue = new LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoRequest();
            inValue.objOT = objOT;
            LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoResponse retVal = ((LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS)(this)).insertarOrdenTrabajo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoResponse> LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS.insertarOrdenTrabajoAsync(LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoRequest request) {
            return base.Channel.insertarOrdenTrabajoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoResponse> insertarOrdenTrabajoAsync(LP2MegaAutos.ServicioOrdenTrabajo.ordenTrabajo objOT) {
            LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoRequest inValue = new LP2MegaAutos.ServicioOrdenTrabajo.insertarOrdenTrabajoRequest();
            inValue.objOT = objOT;
            return ((LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS)(this)).insertarOrdenTrabajoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoResponse LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS.actualizarOrdenTrabajo(LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoRequest request) {
            return base.Channel.actualizarOrdenTrabajo(request);
        }
        
        public int actualizarOrdenTrabajo(LP2MegaAutos.ServicioOrdenTrabajo.ordenTrabajo objOT) {
            LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoRequest inValue = new LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoRequest();
            inValue.objOT = objOT;
            LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoResponse retVal = ((LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS)(this)).actualizarOrdenTrabajo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoResponse> LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS.actualizarOrdenTrabajoAsync(LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoRequest request) {
            return base.Channel.actualizarOrdenTrabajoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoResponse> actualizarOrdenTrabajoAsync(LP2MegaAutos.ServicioOrdenTrabajo.ordenTrabajo objOT) {
            LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoRequest inValue = new LP2MegaAutos.ServicioOrdenTrabajo.actualizarOrdenTrabajoRequest();
            inValue.objOT = objOT;
            return ((LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS)(this)).actualizarOrdenTrabajoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoResponse LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS.listarOrdenTrabajo(LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoRequest request) {
            return base.Channel.listarOrdenTrabajo(request);
        }
        
        public LP2MegaAutos.ServicioOrdenTrabajo.ordenTrabajo[] listarOrdenTrabajo() {
            LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoRequest inValue = new LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoRequest();
            LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoResponse retVal = ((LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS)(this)).listarOrdenTrabajo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoResponse> LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS.listarOrdenTrabajoAsync(LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoRequest request) {
            return base.Channel.listarOrdenTrabajoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoResponse> listarOrdenTrabajoAsync() {
            LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoRequest inValue = new LP2MegaAutos.ServicioOrdenTrabajo.listarOrdenTrabajoRequest();
            return ((LP2MegaAutos.ServicioOrdenTrabajo.OrdenTrabajoWS)(this)).listarOrdenTrabajoAsync(inValue);
        }
    }
}
