//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LP2MegaAutos.ServicioExcel {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.megaautos.com.pe/", ConfigurationName="ServicioExcel.ExcelWS")]
    public interface ExcelWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/buscarPorIdRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/buscarPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioExcel.buscarPorIdResponse buscarPorId(LP2MegaAutos.ServicioExcel.buscarPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/buscarPorIdRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/buscarPorIdResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.buscarPorIdResponse> buscarPorIdAsync(LP2MegaAutos.ServicioExcel.buscarPorIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/insertarArchivoEntradaRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/insertarArchivoEntradaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioExcel.insertarArchivoEntradaResponse insertarArchivoEntrada(LP2MegaAutos.ServicioExcel.insertarArchivoEntradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/insertarArchivoEntradaRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/insertarArchivoEntradaResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.insertarArchivoEntradaResponse> insertarArchivoEntradaAsync(LP2MegaAutos.ServicioExcel.insertarArchivoEntradaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/leerArchivoSalidaRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/leerArchivoSalidaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioExcel.leerArchivoSalidaResponse leerArchivoSalida(LP2MegaAutos.ServicioExcel.leerArchivoSalidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/leerArchivoSalidaRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/leerArchivoSalidaResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.leerArchivoSalidaResponse> leerArchivoSalidaAsync(LP2MegaAutos.ServicioExcel.leerArchivoSalidaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/insertarArchivoSalidaRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/insertarArchivoSalidaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioExcel.insertarArchivoSalidaResponse insertarArchivoSalida(LP2MegaAutos.ServicioExcel.insertarArchivoSalidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/insertarArchivoSalidaRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/insertarArchivoSalidaResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.insertarArchivoSalidaResponse> insertarArchivoSalidaAsync(LP2MegaAutos.ServicioExcel.insertarArchivoSalidaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/leerArchivoEntradaRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/leerArchivoEntradaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioExcel.leerArchivoEntradaResponse leerArchivoEntrada(LP2MegaAutos.ServicioExcel.leerArchivoEntradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/leerArchivoEntradaRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/leerArchivoEntradaResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.leerArchivoEntradaResponse> leerArchivoEntradaAsync(LP2MegaAutos.ServicioExcel.leerArchivoEntradaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/procesarRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/procesarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioExcel.procesarResponse procesar(LP2MegaAutos.ServicioExcel.procesarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/procesarRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/procesarResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.procesarResponse> procesarAsync(LP2MegaAutos.ServicioExcel.procesarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/generarReporteRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/generarReporteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioExcel.generarReporteResponse generarReporte(LP2MegaAutos.ServicioExcel.generarReporteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/generarReporteRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/generarReporteResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.generarReporteResponse> generarReporteAsync(LP2MegaAutos.ServicioExcel.generarReporteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class excel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] archivoField;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaIniField;
        
        private bool fechaIniFieldSpecified;
        
        private int idField;
        
        private sede sedeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
                this.RaisePropertyChanged("archivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaIni {
            get {
                return this.fechaIniField;
            }
            set {
                this.fechaIniField = value;
                this.RaisePropertyChanged("fechaIni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaIniSpecified {
            get {
                return this.fechaIniFieldSpecified;
            }
            set {
                this.fechaIniFieldSpecified = value;
                this.RaisePropertyChanged("fechaIniSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public sede sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class sede : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string direccionField;
        
        private string distritoField;
        
        private int idField;
        
        private string nombreField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class vehiculo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string placaField;
        
        private cliente propietarioField;
        
        private string tipoVehiculoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public cliente propietario {
            get {
                return this.propietarioField;
            }
            set {
                this.propietarioField = value;
                this.RaisePropertyChanged("propietario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoVehiculo {
            get {
                return this.tipoVehiculoField;
            }
            set {
                this.tipoVehiculoField = value;
                this.RaisePropertyChanged("tipoVehiculo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoField;
        
        private int idField;
        
        private string nombreField;
        
        private string numDocumentoField;
        
        private string telefonoField;
        
        private string tipoClienteField;
        
        private string tipoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string numDocumento {
            get {
                return this.numDocumentoField;
            }
            set {
                this.numDocumentoField = value;
                this.RaisePropertyChanged("numDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipoCliente {
            get {
                return this.tipoClienteField;
            }
            set {
                this.tipoClienteField = value;
                this.RaisePropertyChanged("tipoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class servicio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoServicioField;
        
        private string descripcionField;
        
        private int idField;
        
        private string nombreField;
        
        private string tipoServicioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoServicio {
            get {
                return this.codigoServicioField;
            }
            set {
                this.codigoServicioField = value;
                this.RaisePropertyChanged("codigoServicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tipoServicio {
            get {
                return this.tipoServicioField;
            }
            set {
                this.tipoServicioField = value;
                this.RaisePropertyChanged("tipoServicio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class comprobantePago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idField;
        
        private double montoField;
        
        private string numeroComprobanteField;
        
        private ordenTrabajo ordenTrabajoField;
        
        private string tipoComprobanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string numeroComprobante {
            get {
                return this.numeroComprobanteField;
            }
            set {
                this.numeroComprobanteField = value;
                this.RaisePropertyChanged("numeroComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ordenTrabajo ordenTrabajo {
            get {
                return this.ordenTrabajoField;
            }
            set {
                this.ordenTrabajoField = value;
                this.RaisePropertyChanged("ordenTrabajo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
                this.RaisePropertyChanged("tipoComprobante");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class ordenTrabajo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private cliente clienteField;
        
        private double comprasRptoField;
        
        private comprobantePago comprobantePagoField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idField;
        
        private double margenBrutoField;
        
        private string numeroOrdenField;
        
        private double porcentajeField;
        
        private double salidasAlmacenField;
        
        private sede sedeField;
        
        private double serTerTallerField;
        
        private double servTercerosField;
        
        private servicio[] serviciosField;
        
        private string tipoSiniestroField;
        
        private double totalEgresosField;
        
        private double totalIngresosField;
        
        private vehiculo vehiculoField;
        
        private double mObraMecanicaField;
        
        private double mObraPinturaField;
        
        private double mObraPlanchadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double comprasRpto {
            get {
                return this.comprasRptoField;
            }
            set {
                this.comprasRptoField = value;
                this.RaisePropertyChanged("comprasRpto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public comprobantePago comprobantePago {
            get {
                return this.comprobantePagoField;
            }
            set {
                this.comprobantePagoField = value;
                this.RaisePropertyChanged("comprobantePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double margenBruto {
            get {
                return this.margenBrutoField;
            }
            set {
                this.margenBrutoField = value;
                this.RaisePropertyChanged("margenBruto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string numeroOrden {
            get {
                return this.numeroOrdenField;
            }
            set {
                this.numeroOrdenField = value;
                this.RaisePropertyChanged("numeroOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double porcentaje {
            get {
                return this.porcentajeField;
            }
            set {
                this.porcentajeField = value;
                this.RaisePropertyChanged("porcentaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double salidasAlmacen {
            get {
                return this.salidasAlmacenField;
            }
            set {
                this.salidasAlmacenField = value;
                this.RaisePropertyChanged("salidasAlmacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public sede sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double serTerTaller {
            get {
                return this.serTerTallerField;
            }
            set {
                this.serTerTallerField = value;
                this.RaisePropertyChanged("serTerTaller");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public double servTerceros {
            get {
                return this.servTercerosField;
            }
            set {
                this.servTercerosField = value;
                this.RaisePropertyChanged("servTerceros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("servicios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public servicio[] servicios {
            get {
                return this.serviciosField;
            }
            set {
                this.serviciosField = value;
                this.RaisePropertyChanged("servicios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string tipoSiniestro {
            get {
                return this.tipoSiniestroField;
            }
            set {
                this.tipoSiniestroField = value;
                this.RaisePropertyChanged("tipoSiniestro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public double totalEgresos {
            get {
                return this.totalEgresosField;
            }
            set {
                this.totalEgresosField = value;
                this.RaisePropertyChanged("totalEgresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public double totalIngresos {
            get {
                return this.totalIngresosField;
            }
            set {
                this.totalIngresosField = value;
                this.RaisePropertyChanged("totalIngresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public vehiculo vehiculo {
            get {
                return this.vehiculoField;
            }
            set {
                this.vehiculoField = value;
                this.RaisePropertyChanged("vehiculo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public double mObraMecanica {
            get {
                return this.mObraMecanicaField;
            }
            set {
                this.mObraMecanicaField = value;
                this.RaisePropertyChanged("mObraMecanica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public double mObraPintura {
            get {
                return this.mObraPinturaField;
            }
            set {
                this.mObraPinturaField = value;
                this.RaisePropertyChanged("mObraPintura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public double mObraPlanchado {
            get {
                return this.mObraPlanchadoField;
            }
            set {
                this.mObraPlanchadoField = value;
                this.RaisePropertyChanged("mObraPlanchado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class detalleReporte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cuentaField;
        
        private System.Nullable<double>[] montosField;
        
        private ordenTrabajo[] ordenesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("cuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("montos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<double>[] montos {
            get {
                return this.montosField;
            }
            set {
                this.montosField = value;
                this.RaisePropertyChanged("montos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ordenes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public ordenTrabajo[] ordenes {
            get {
                return this.ordenesField;
            }
            set {
                this.ordenesField = value;
                this.RaisePropertyChanged("ordenes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class reporte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private detalleReporte[] detalleField;
        
        private double egresosField;
        
        private bool egresosFieldSpecified;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaInicioField;
        
        private bool fechaInicioFieldSpecified;
        
        private int idExcelEntradaField;
        
        private int idExcelSalidaField;
        
        private int idReporteField;
        
        private int idUsuarioField;
        
        private double ingresosField;
        
        private bool ingresosFieldSpecified;
        
        private string nombreUsuarioField;
        
        private sede sedeField;
        
        private string tipoReporteField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detalle", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public detalleReporte[] detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
                this.RaisePropertyChanged("detalle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double egresos {
            get {
                return this.egresosField;
            }
            set {
                this.egresosField = value;
                this.RaisePropertyChanged("egresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool egresosSpecified {
            get {
                return this.egresosFieldSpecified;
            }
            set {
                this.egresosFieldSpecified = value;
                this.RaisePropertyChanged("egresosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified {
            get {
                return this.fechaInicioFieldSpecified;
            }
            set {
                this.fechaInicioFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idExcelEntrada {
            get {
                return this.idExcelEntradaField;
            }
            set {
                this.idExcelEntradaField = value;
                this.RaisePropertyChanged("idExcelEntrada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idExcelSalida {
            get {
                return this.idExcelSalidaField;
            }
            set {
                this.idExcelSalidaField = value;
                this.RaisePropertyChanged("idExcelSalida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idReporte {
            get {
                return this.idReporteField;
            }
            set {
                this.idReporteField = value;
                this.RaisePropertyChanged("idReporte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double ingresos {
            get {
                return this.ingresosField;
            }
            set {
                this.ingresosField = value;
                this.RaisePropertyChanged("ingresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ingresosSpecified {
            get {
                return this.ingresosFieldSpecified;
            }
            set {
                this.ingresosFieldSpecified = value;
                this.RaisePropertyChanged("ingresosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public sede sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string tipoReporte {
            get {
                return this.tipoReporteField;
            }
            set {
                this.tipoReporteField = value;
                this.RaisePropertyChanged("tipoReporte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPorId", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class buscarPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idExcel;
        
        public buscarPorIdRequest() {
        }
        
        public buscarPorIdRequest(int idExcel) {
            this.idExcel = idExcel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPorIdResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class buscarPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioExcel.excel @return;
        
        public buscarPorIdResponse() {
        }
        
        public buscarPorIdResponse(LP2MegaAutos.ServicioExcel.excel @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarArchivoEntrada", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class insertarArchivoEntradaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioExcel.excel archivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public insertarArchivoEntradaRequest() {
        }
        
        public insertarArchivoEntradaRequest(LP2MegaAutos.ServicioExcel.excel archivo, int arg1) {
            this.archivo = archivo;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarArchivoEntradaResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class insertarArchivoEntradaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarArchivoEntradaResponse() {
        }
        
        public insertarArchivoEntradaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leerArchivoSalida", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class leerArchivoSalidaRequest {
        
        public leerArchivoSalidaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leerArchivoSalidaResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class leerArchivoSalidaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioExcel.excel @return;
        
        public leerArchivoSalidaResponse() {
        }
        
        public leerArchivoSalidaResponse(LP2MegaAutos.ServicioExcel.excel @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarArchivoSalida", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class insertarArchivoSalidaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioExcel.excel archivo;
        
        public insertarArchivoSalidaRequest() {
        }
        
        public insertarArchivoSalidaRequest(LP2MegaAutos.ServicioExcel.excel archivo) {
            this.archivo = archivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarArchivoSalidaResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class insertarArchivoSalidaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarArchivoSalidaResponse() {
        }
        
        public insertarArchivoSalidaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leerArchivoEntrada", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class leerArchivoEntradaRequest {
        
        public leerArchivoEntradaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leerArchivoEntradaResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class leerArchivoEntradaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioExcel.excel @return;
        
        public leerArchivoEntradaResponse() {
        }
        
        public leerArchivoEntradaResponse(LP2MegaAutos.ServicioExcel.excel @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="procesar", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class procesarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioExcel.excel arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg8;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg9;
        
        public procesarRequest() {
        }
        
        public procesarRequest(LP2MegaAutos.ServicioExcel.excel arg0, string arg1, string arg2, string arg3, int arg4, System.DateTime arg5, System.DateTime arg6, int arg7, int arg8, int arg9) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
            this.arg9 = arg9;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="procesarResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class procesarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioExcel.reporte @return;
        
        public procesarResponse() {
        }
        
        public procesarResponse(LP2MegaAutos.ServicioExcel.reporte @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporte", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class generarReporteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSede;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string titulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idReporte;
        
        public generarReporteRequest() {
        }
        
        public generarReporteRequest(string fechaInicio, string fechaFin, string tipo, int idSede, int idUsuario, string titulo, int idReporte) {
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
            this.tipo = tipo;
            this.idSede = idSede;
            this.idUsuario = idUsuario;
            this.titulo = titulo;
            this.idReporte = idReporte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class generarReporteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioExcel.reporte @return;
        
        public generarReporteResponse() {
        }
        
        public generarReporteResponse(LP2MegaAutos.ServicioExcel.reporte @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExcelWSChannel : LP2MegaAutos.ServicioExcel.ExcelWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExcelWSClient : System.ServiceModel.ClientBase<LP2MegaAutos.ServicioExcel.ExcelWS>, LP2MegaAutos.ServicioExcel.ExcelWS {
        
        public ExcelWSClient() {
        }
        
        public ExcelWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExcelWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExcelWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExcelWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioExcel.buscarPorIdResponse LP2MegaAutos.ServicioExcel.ExcelWS.buscarPorId(LP2MegaAutos.ServicioExcel.buscarPorIdRequest request) {
            return base.Channel.buscarPorId(request);
        }
        
        public LP2MegaAutos.ServicioExcel.excel buscarPorId(int idExcel) {
            LP2MegaAutos.ServicioExcel.buscarPorIdRequest inValue = new LP2MegaAutos.ServicioExcel.buscarPorIdRequest();
            inValue.idExcel = idExcel;
            LP2MegaAutos.ServicioExcel.buscarPorIdResponse retVal = ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).buscarPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.buscarPorIdResponse> LP2MegaAutos.ServicioExcel.ExcelWS.buscarPorIdAsync(LP2MegaAutos.ServicioExcel.buscarPorIdRequest request) {
            return base.Channel.buscarPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.buscarPorIdResponse> buscarPorIdAsync(int idExcel) {
            LP2MegaAutos.ServicioExcel.buscarPorIdRequest inValue = new LP2MegaAutos.ServicioExcel.buscarPorIdRequest();
            inValue.idExcel = idExcel;
            return ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).buscarPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioExcel.insertarArchivoEntradaResponse LP2MegaAutos.ServicioExcel.ExcelWS.insertarArchivoEntrada(LP2MegaAutos.ServicioExcel.insertarArchivoEntradaRequest request) {
            return base.Channel.insertarArchivoEntrada(request);
        }
        
        public int insertarArchivoEntrada(LP2MegaAutos.ServicioExcel.excel archivo, int arg1) {
            LP2MegaAutos.ServicioExcel.insertarArchivoEntradaRequest inValue = new LP2MegaAutos.ServicioExcel.insertarArchivoEntradaRequest();
            inValue.archivo = archivo;
            inValue.arg1 = arg1;
            LP2MegaAutos.ServicioExcel.insertarArchivoEntradaResponse retVal = ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).insertarArchivoEntrada(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.insertarArchivoEntradaResponse> LP2MegaAutos.ServicioExcel.ExcelWS.insertarArchivoEntradaAsync(LP2MegaAutos.ServicioExcel.insertarArchivoEntradaRequest request) {
            return base.Channel.insertarArchivoEntradaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.insertarArchivoEntradaResponse> insertarArchivoEntradaAsync(LP2MegaAutos.ServicioExcel.excel archivo, int arg1) {
            LP2MegaAutos.ServicioExcel.insertarArchivoEntradaRequest inValue = new LP2MegaAutos.ServicioExcel.insertarArchivoEntradaRequest();
            inValue.archivo = archivo;
            inValue.arg1 = arg1;
            return ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).insertarArchivoEntradaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioExcel.leerArchivoSalidaResponse LP2MegaAutos.ServicioExcel.ExcelWS.leerArchivoSalida(LP2MegaAutos.ServicioExcel.leerArchivoSalidaRequest request) {
            return base.Channel.leerArchivoSalida(request);
        }
        
        public LP2MegaAutos.ServicioExcel.excel leerArchivoSalida() {
            LP2MegaAutos.ServicioExcel.leerArchivoSalidaRequest inValue = new LP2MegaAutos.ServicioExcel.leerArchivoSalidaRequest();
            LP2MegaAutos.ServicioExcel.leerArchivoSalidaResponse retVal = ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).leerArchivoSalida(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.leerArchivoSalidaResponse> LP2MegaAutos.ServicioExcel.ExcelWS.leerArchivoSalidaAsync(LP2MegaAutos.ServicioExcel.leerArchivoSalidaRequest request) {
            return base.Channel.leerArchivoSalidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.leerArchivoSalidaResponse> leerArchivoSalidaAsync() {
            LP2MegaAutos.ServicioExcel.leerArchivoSalidaRequest inValue = new LP2MegaAutos.ServicioExcel.leerArchivoSalidaRequest();
            return ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).leerArchivoSalidaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioExcel.insertarArchivoSalidaResponse LP2MegaAutos.ServicioExcel.ExcelWS.insertarArchivoSalida(LP2MegaAutos.ServicioExcel.insertarArchivoSalidaRequest request) {
            return base.Channel.insertarArchivoSalida(request);
        }
        
        public int insertarArchivoSalida(LP2MegaAutos.ServicioExcel.excel archivo) {
            LP2MegaAutos.ServicioExcel.insertarArchivoSalidaRequest inValue = new LP2MegaAutos.ServicioExcel.insertarArchivoSalidaRequest();
            inValue.archivo = archivo;
            LP2MegaAutos.ServicioExcel.insertarArchivoSalidaResponse retVal = ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).insertarArchivoSalida(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.insertarArchivoSalidaResponse> LP2MegaAutos.ServicioExcel.ExcelWS.insertarArchivoSalidaAsync(LP2MegaAutos.ServicioExcel.insertarArchivoSalidaRequest request) {
            return base.Channel.insertarArchivoSalidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.insertarArchivoSalidaResponse> insertarArchivoSalidaAsync(LP2MegaAutos.ServicioExcel.excel archivo) {
            LP2MegaAutos.ServicioExcel.insertarArchivoSalidaRequest inValue = new LP2MegaAutos.ServicioExcel.insertarArchivoSalidaRequest();
            inValue.archivo = archivo;
            return ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).insertarArchivoSalidaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioExcel.leerArchivoEntradaResponse LP2MegaAutos.ServicioExcel.ExcelWS.leerArchivoEntrada(LP2MegaAutos.ServicioExcel.leerArchivoEntradaRequest request) {
            return base.Channel.leerArchivoEntrada(request);
        }
        
        public LP2MegaAutos.ServicioExcel.excel leerArchivoEntrada() {
            LP2MegaAutos.ServicioExcel.leerArchivoEntradaRequest inValue = new LP2MegaAutos.ServicioExcel.leerArchivoEntradaRequest();
            LP2MegaAutos.ServicioExcel.leerArchivoEntradaResponse retVal = ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).leerArchivoEntrada(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.leerArchivoEntradaResponse> LP2MegaAutos.ServicioExcel.ExcelWS.leerArchivoEntradaAsync(LP2MegaAutos.ServicioExcel.leerArchivoEntradaRequest request) {
            return base.Channel.leerArchivoEntradaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.leerArchivoEntradaResponse> leerArchivoEntradaAsync() {
            LP2MegaAutos.ServicioExcel.leerArchivoEntradaRequest inValue = new LP2MegaAutos.ServicioExcel.leerArchivoEntradaRequest();
            return ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).leerArchivoEntradaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioExcel.procesarResponse LP2MegaAutos.ServicioExcel.ExcelWS.procesar(LP2MegaAutos.ServicioExcel.procesarRequest request) {
            return base.Channel.procesar(request);
        }
        
        public LP2MegaAutos.ServicioExcel.reporte procesar(LP2MegaAutos.ServicioExcel.excel arg0, string arg1, string arg2, string arg3, int arg4, System.DateTime arg5, System.DateTime arg6, int arg7, int arg8, int arg9) {
            LP2MegaAutos.ServicioExcel.procesarRequest inValue = new LP2MegaAutos.ServicioExcel.procesarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            inValue.arg9 = arg9;
            LP2MegaAutos.ServicioExcel.procesarResponse retVal = ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).procesar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.procesarResponse> LP2MegaAutos.ServicioExcel.ExcelWS.procesarAsync(LP2MegaAutos.ServicioExcel.procesarRequest request) {
            return base.Channel.procesarAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.procesarResponse> procesarAsync(LP2MegaAutos.ServicioExcel.excel arg0, string arg1, string arg2, string arg3, int arg4, System.DateTime arg5, System.DateTime arg6, int arg7, int arg8, int arg9) {
            LP2MegaAutos.ServicioExcel.procesarRequest inValue = new LP2MegaAutos.ServicioExcel.procesarRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            inValue.arg9 = arg9;
            return ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).procesarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioExcel.generarReporteResponse LP2MegaAutos.ServicioExcel.ExcelWS.generarReporte(LP2MegaAutos.ServicioExcel.generarReporteRequest request) {
            return base.Channel.generarReporte(request);
        }
        
        public LP2MegaAutos.ServicioExcel.reporte generarReporte(string fechaInicio, string fechaFin, string tipo, int idSede, int idUsuario, string titulo, int idReporte) {
            LP2MegaAutos.ServicioExcel.generarReporteRequest inValue = new LP2MegaAutos.ServicioExcel.generarReporteRequest();
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            inValue.tipo = tipo;
            inValue.idSede = idSede;
            inValue.idUsuario = idUsuario;
            inValue.titulo = titulo;
            inValue.idReporte = idReporte;
            LP2MegaAutos.ServicioExcel.generarReporteResponse retVal = ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).generarReporte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.generarReporteResponse> LP2MegaAutos.ServicioExcel.ExcelWS.generarReporteAsync(LP2MegaAutos.ServicioExcel.generarReporteRequest request) {
            return base.Channel.generarReporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.generarReporteResponse> generarReporteAsync(string fechaInicio, string fechaFin, string tipo, int idSede, int idUsuario, string titulo, int idReporte) {
            LP2MegaAutos.ServicioExcel.generarReporteRequest inValue = new LP2MegaAutos.ServicioExcel.generarReporteRequest();
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            inValue.tipo = tipo;
            inValue.idSede = idSede;
            inValue.idUsuario = idUsuario;
            inValue.titulo = titulo;
            inValue.idReporte = idReporte;
            return ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).generarReporteAsync(inValue);
        }
    }
}
