//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LP2MegaAutos.ServicioExcel {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.megaautos.com.pe/", ConfigurationName="ServicioExcel.ExcelWS")]
    public interface ExcelWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/leerExcel1Request", ReplyAction="http://services.megaautos.com.pe/ExcelWS/leerExcel1Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioExcel.leerExcel1Response leerExcel1(LP2MegaAutos.ServicioExcel.leerExcel1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/leerExcel1Request", ReplyAction="http://services.megaautos.com.pe/ExcelWS/leerExcel1Response")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.leerExcel1Response> leerExcel1Async(LP2MegaAutos.ServicioExcel.leerExcel1Request request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/enviarExcelRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/enviarExcelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioExcel.enviarExcelResponse enviarExcel(LP2MegaAutos.ServicioExcel.enviarExcelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/ExcelWS/enviarExcelRequest", ReplyAction="http://services.megaautos.com.pe/ExcelWS/enviarExcelResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.enviarExcelResponse> enviarExcelAsync(LP2MegaAutos.ServicioExcel.enviarExcelRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class excel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] archivoField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] archivo {
            get {
                return this.archivoField;
            }
            set {
                this.archivoField = value;
                this.RaisePropertyChanged("archivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leerExcel1", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class leerExcel1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioExcel.excel archivo;
        
        public leerExcel1Request() {
        }
        
        public leerExcel1Request(LP2MegaAutos.ServicioExcel.excel archivo) {
            this.archivo = archivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leerExcel1Response", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class leerExcel1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public leerExcel1Response() {
        }
        
        public leerExcel1Response(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarExcel", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class enviarExcelRequest {
        
        public enviarExcelRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarExcelResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class enviarExcelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioExcel.excel @return;
        
        public enviarExcelResponse() {
        }
        
        public enviarExcelResponse(LP2MegaAutos.ServicioExcel.excel @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExcelWSChannel : LP2MegaAutos.ServicioExcel.ExcelWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExcelWSClient : System.ServiceModel.ClientBase<LP2MegaAutos.ServicioExcel.ExcelWS>, LP2MegaAutos.ServicioExcel.ExcelWS {
        
        public ExcelWSClient() {
        }
        
        public ExcelWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExcelWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExcelWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExcelWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioExcel.leerExcel1Response LP2MegaAutos.ServicioExcel.ExcelWS.leerExcel1(LP2MegaAutos.ServicioExcel.leerExcel1Request request) {
            return base.Channel.leerExcel1(request);
        }
        
        public int leerExcel1(LP2MegaAutos.ServicioExcel.excel archivo) {
            LP2MegaAutos.ServicioExcel.leerExcel1Request inValue = new LP2MegaAutos.ServicioExcel.leerExcel1Request();
            inValue.archivo = archivo;
            LP2MegaAutos.ServicioExcel.leerExcel1Response retVal = ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).leerExcel1(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.leerExcel1Response> LP2MegaAutos.ServicioExcel.ExcelWS.leerExcel1Async(LP2MegaAutos.ServicioExcel.leerExcel1Request request) {
            return base.Channel.leerExcel1Async(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.leerExcel1Response> leerExcel1Async(LP2MegaAutos.ServicioExcel.excel archivo) {
            LP2MegaAutos.ServicioExcel.leerExcel1Request inValue = new LP2MegaAutos.ServicioExcel.leerExcel1Request();
            inValue.archivo = archivo;
            return ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).leerExcel1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioExcel.enviarExcelResponse LP2MegaAutos.ServicioExcel.ExcelWS.enviarExcel(LP2MegaAutos.ServicioExcel.enviarExcelRequest request) {
            return base.Channel.enviarExcel(request);
        }
        
        public LP2MegaAutos.ServicioExcel.excel enviarExcel() {
            LP2MegaAutos.ServicioExcel.enviarExcelRequest inValue = new LP2MegaAutos.ServicioExcel.enviarExcelRequest();
            LP2MegaAutos.ServicioExcel.enviarExcelResponse retVal = ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).enviarExcel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.enviarExcelResponse> LP2MegaAutos.ServicioExcel.ExcelWS.enviarExcelAsync(LP2MegaAutos.ServicioExcel.enviarExcelRequest request) {
            return base.Channel.enviarExcelAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioExcel.enviarExcelResponse> enviarExcelAsync() {
            LP2MegaAutos.ServicioExcel.enviarExcelRequest inValue = new LP2MegaAutos.ServicioExcel.enviarExcelRequest();
            return ((LP2MegaAutos.ServicioExcel.ExcelWS)(this)).enviarExcelAsync(inValue);
        }
    }
}
