//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LP2MegaAutos.ServicioEmpresa {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.megaautos.com.pe/", ConfigurationName="ServicioEmpresa.EmpresaWS")]
    public interface EmpresaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/EmpresaWS/listarEmpresaRequest", ReplyAction="http://services.megaautos.com.pe/EmpresaWS/listarEmpresaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioEmpresa.listarEmpresaResponse listarEmpresa(LP2MegaAutos.ServicioEmpresa.listarEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/EmpresaWS/listarEmpresaRequest", ReplyAction="http://services.megaautos.com.pe/EmpresaWS/listarEmpresaResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioEmpresa.listarEmpresaResponse> listarEmpresaAsync(LP2MegaAutos.ServicioEmpresa.listarEmpresaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/EmpresaWS/insertarEmpresaRequest", ReplyAction="http://services.megaautos.com.pe/EmpresaWS/insertarEmpresaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioEmpresa.insertarEmpresaResponse insertarEmpresa(LP2MegaAutos.ServicioEmpresa.insertarEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/EmpresaWS/insertarEmpresaRequest", ReplyAction="http://services.megaautos.com.pe/EmpresaWS/insertarEmpresaResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioEmpresa.insertarEmpresaResponse> insertarEmpresaAsync(LP2MegaAutos.ServicioEmpresa.insertarEmpresaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/EmpresaWS/eliminarEmpresaRequest", ReplyAction="http://services.megaautos.com.pe/EmpresaWS/eliminarEmpresaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioEmpresa.eliminarEmpresaResponse eliminarEmpresa(LP2MegaAutos.ServicioEmpresa.eliminarEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/EmpresaWS/eliminarEmpresaRequest", ReplyAction="http://services.megaautos.com.pe/EmpresaWS/eliminarEmpresaResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioEmpresa.eliminarEmpresaResponse> eliminarEmpresaAsync(LP2MegaAutos.ServicioEmpresa.eliminarEmpresaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/EmpresaWS/actualizarEmpresaRequest", ReplyAction="http://services.megaautos.com.pe/EmpresaWS/actualizarEmpresaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioEmpresa.actualizarEmpresaResponse actualizarEmpresa(LP2MegaAutos.ServicioEmpresa.actualizarEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/EmpresaWS/actualizarEmpresaRequest", ReplyAction="http://services.megaautos.com.pe/EmpresaWS/actualizarEmpresaResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioEmpresa.actualizarEmpresaResponse> actualizarEmpresaAsync(LP2MegaAutos.ServicioEmpresa.actualizarEmpresaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class empresa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresa", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class listarEmpresaRequest {
        
        public listarEmpresaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresaResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class listarEmpresaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioEmpresa.empresa[] @return;
        
        public listarEmpresaResponse() {
        }
        
        public listarEmpresaResponse(LP2MegaAutos.ServicioEmpresa.empresa[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEmpresa", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class insertarEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioEmpresa.empresa objEmrpesa;
        
        public insertarEmpresaRequest() {
        }
        
        public insertarEmpresaRequest(LP2MegaAutos.ServicioEmpresa.empresa objEmrpesa) {
            this.objEmrpesa = objEmrpesa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEmpresaResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class insertarEmpresaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEmpresaResponse() {
        }
        
        public insertarEmpresaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpresa", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class eliminarEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEmpresa;
        
        public eliminarEmpresaRequest() {
        }
        
        public eliminarEmpresaRequest(int idEmpresa) {
            this.idEmpresa = idEmpresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpresaResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class eliminarEmpresaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarEmpresaResponse() {
        }
        
        public eliminarEmpresaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEmpresa", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class actualizarEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioEmpresa.empresa objEmpresa;
        
        public actualizarEmpresaRequest() {
        }
        
        public actualizarEmpresaRequest(LP2MegaAutos.ServicioEmpresa.empresa objEmpresa) {
            this.objEmpresa = objEmpresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEmpresaResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class actualizarEmpresaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarEmpresaResponse() {
        }
        
        public actualizarEmpresaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmpresaWSChannel : LP2MegaAutos.ServicioEmpresa.EmpresaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpresaWSClient : System.ServiceModel.ClientBase<LP2MegaAutos.ServicioEmpresa.EmpresaWS>, LP2MegaAutos.ServicioEmpresa.EmpresaWS {
        
        public EmpresaWSClient() {
        }
        
        public EmpresaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpresaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioEmpresa.listarEmpresaResponse LP2MegaAutos.ServicioEmpresa.EmpresaWS.listarEmpresa(LP2MegaAutos.ServicioEmpresa.listarEmpresaRequest request) {
            return base.Channel.listarEmpresa(request);
        }
        
        public LP2MegaAutos.ServicioEmpresa.empresa[] listarEmpresa() {
            LP2MegaAutos.ServicioEmpresa.listarEmpresaRequest inValue = new LP2MegaAutos.ServicioEmpresa.listarEmpresaRequest();
            LP2MegaAutos.ServicioEmpresa.listarEmpresaResponse retVal = ((LP2MegaAutos.ServicioEmpresa.EmpresaWS)(this)).listarEmpresa(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioEmpresa.listarEmpresaResponse> LP2MegaAutos.ServicioEmpresa.EmpresaWS.listarEmpresaAsync(LP2MegaAutos.ServicioEmpresa.listarEmpresaRequest request) {
            return base.Channel.listarEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioEmpresa.listarEmpresaResponse> listarEmpresaAsync() {
            LP2MegaAutos.ServicioEmpresa.listarEmpresaRequest inValue = new LP2MegaAutos.ServicioEmpresa.listarEmpresaRequest();
            return ((LP2MegaAutos.ServicioEmpresa.EmpresaWS)(this)).listarEmpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioEmpresa.insertarEmpresaResponse LP2MegaAutos.ServicioEmpresa.EmpresaWS.insertarEmpresa(LP2MegaAutos.ServicioEmpresa.insertarEmpresaRequest request) {
            return base.Channel.insertarEmpresa(request);
        }
        
        public int insertarEmpresa(LP2MegaAutos.ServicioEmpresa.empresa objEmrpesa) {
            LP2MegaAutos.ServicioEmpresa.insertarEmpresaRequest inValue = new LP2MegaAutos.ServicioEmpresa.insertarEmpresaRequest();
            inValue.objEmrpesa = objEmrpesa;
            LP2MegaAutos.ServicioEmpresa.insertarEmpresaResponse retVal = ((LP2MegaAutos.ServicioEmpresa.EmpresaWS)(this)).insertarEmpresa(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioEmpresa.insertarEmpresaResponse> LP2MegaAutos.ServicioEmpresa.EmpresaWS.insertarEmpresaAsync(LP2MegaAutos.ServicioEmpresa.insertarEmpresaRequest request) {
            return base.Channel.insertarEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioEmpresa.insertarEmpresaResponse> insertarEmpresaAsync(LP2MegaAutos.ServicioEmpresa.empresa objEmrpesa) {
            LP2MegaAutos.ServicioEmpresa.insertarEmpresaRequest inValue = new LP2MegaAutos.ServicioEmpresa.insertarEmpresaRequest();
            inValue.objEmrpesa = objEmrpesa;
            return ((LP2MegaAutos.ServicioEmpresa.EmpresaWS)(this)).insertarEmpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioEmpresa.eliminarEmpresaResponse LP2MegaAutos.ServicioEmpresa.EmpresaWS.eliminarEmpresa(LP2MegaAutos.ServicioEmpresa.eliminarEmpresaRequest request) {
            return base.Channel.eliminarEmpresa(request);
        }
        
        public int eliminarEmpresa(int idEmpresa) {
            LP2MegaAutos.ServicioEmpresa.eliminarEmpresaRequest inValue = new LP2MegaAutos.ServicioEmpresa.eliminarEmpresaRequest();
            inValue.idEmpresa = idEmpresa;
            LP2MegaAutos.ServicioEmpresa.eliminarEmpresaResponse retVal = ((LP2MegaAutos.ServicioEmpresa.EmpresaWS)(this)).eliminarEmpresa(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioEmpresa.eliminarEmpresaResponse> LP2MegaAutos.ServicioEmpresa.EmpresaWS.eliminarEmpresaAsync(LP2MegaAutos.ServicioEmpresa.eliminarEmpresaRequest request) {
            return base.Channel.eliminarEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioEmpresa.eliminarEmpresaResponse> eliminarEmpresaAsync(int idEmpresa) {
            LP2MegaAutos.ServicioEmpresa.eliminarEmpresaRequest inValue = new LP2MegaAutos.ServicioEmpresa.eliminarEmpresaRequest();
            inValue.idEmpresa = idEmpresa;
            return ((LP2MegaAutos.ServicioEmpresa.EmpresaWS)(this)).eliminarEmpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioEmpresa.actualizarEmpresaResponse LP2MegaAutos.ServicioEmpresa.EmpresaWS.actualizarEmpresa(LP2MegaAutos.ServicioEmpresa.actualizarEmpresaRequest request) {
            return base.Channel.actualizarEmpresa(request);
        }
        
        public int actualizarEmpresa(LP2MegaAutos.ServicioEmpresa.empresa objEmpresa) {
            LP2MegaAutos.ServicioEmpresa.actualizarEmpresaRequest inValue = new LP2MegaAutos.ServicioEmpresa.actualizarEmpresaRequest();
            inValue.objEmpresa = objEmpresa;
            LP2MegaAutos.ServicioEmpresa.actualizarEmpresaResponse retVal = ((LP2MegaAutos.ServicioEmpresa.EmpresaWS)(this)).actualizarEmpresa(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioEmpresa.actualizarEmpresaResponse> LP2MegaAutos.ServicioEmpresa.EmpresaWS.actualizarEmpresaAsync(LP2MegaAutos.ServicioEmpresa.actualizarEmpresaRequest request) {
            return base.Channel.actualizarEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioEmpresa.actualizarEmpresaResponse> actualizarEmpresaAsync(LP2MegaAutos.ServicioEmpresa.empresa objEmpresa) {
            LP2MegaAutos.ServicioEmpresa.actualizarEmpresaRequest inValue = new LP2MegaAutos.ServicioEmpresa.actualizarEmpresaRequest();
            inValue.objEmpresa = objEmpresa;
            return ((LP2MegaAutos.ServicioEmpresa.EmpresaWS)(this)).actualizarEmpresaAsync(inValue);
        }
    }
}
