//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LP2MegaAutos.ServicioCuentaContable {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.megaautos.com.pe/", ConfigurationName="ServicioCuentaContable.CuentaContableWS")]
    public interface CuentaContableWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/CuentaContableWS/actualizarCuentaContableRequest" +
            "", ReplyAction="http://services.megaautos.com.pe/CuentaContableWS/actualizarCuentaContableRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableResponse actualizarCuentaContable(LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/CuentaContableWS/actualizarCuentaContableRequest" +
            "", ReplyAction="http://services.megaautos.com.pe/CuentaContableWS/actualizarCuentaContableRespons" +
            "e")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableResponse> actualizarCuentaContableAsync(LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/CuentaContableWS/insertarCuentaContableRequest", ReplyAction="http://services.megaautos.com.pe/CuentaContableWS/insertarCuentaContableResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableResponse insertarCuentaContable(LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/CuentaContableWS/insertarCuentaContableRequest", ReplyAction="http://services.megaautos.com.pe/CuentaContableWS/insertarCuentaContableResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableResponse> insertarCuentaContableAsync(LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/CuentaContableWS/listarCuentaContableRequest", ReplyAction="http://services.megaautos.com.pe/CuentaContableWS/listarCuentaContableResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioCuentaContable.listarCuentaContableResponse listarCuentaContable(LP2MegaAutos.ServicioCuentaContable.listarCuentaContableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/CuentaContableWS/listarCuentaContableRequest", ReplyAction="http://services.megaautos.com.pe/CuentaContableWS/listarCuentaContableResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioCuentaContable.listarCuentaContableResponse> listarCuentaContableAsync(LP2MegaAutos.ServicioCuentaContable.listarCuentaContableRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/CuentaContableWS/eliminarCuentaContableRequest", ReplyAction="http://services.megaautos.com.pe/CuentaContableWS/eliminarCuentaContableResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableResponse eliminarCuentaContable(LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.megaautos.com.pe/CuentaContableWS/eliminarCuentaContableRequest", ReplyAction="http://services.megaautos.com.pe/CuentaContableWS/eliminarCuentaContableResponse")]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableResponse> eliminarCuentaContableAsync(LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class cuentaContable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private double montoEgresosField;
        
        private double montoIngresosField;
        
        private string nombreField;
        
        private ordenTrabajo[] ordenesTrabajoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double montoEgresos {
            get {
                return this.montoEgresosField;
            }
            set {
                this.montoEgresosField = value;
                this.RaisePropertyChanged("montoEgresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double montoIngresos {
            get {
                return this.montoIngresosField;
            }
            set {
                this.montoIngresosField = value;
                this.RaisePropertyChanged("montoIngresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ordenesTrabajo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public ordenTrabajo[] ordenesTrabajo {
            get {
                return this.ordenesTrabajoField;
            }
            set {
                this.ordenesTrabajoField = value;
                this.RaisePropertyChanged("ordenesTrabajo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class ordenTrabajo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private cliente clienteField;
        
        private comprobantePago comprobantePagoField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idField;
        
        private string numeroOrdenField;
        
        private sede sedeField;
        
        private double totalEgresosField;
        
        private double totalIngresosField;
        
        private vehiculo vehiculoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public comprobantePago comprobantePago {
            get {
                return this.comprobantePagoField;
            }
            set {
                this.comprobantePagoField = value;
                this.RaisePropertyChanged("comprobantePago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numeroOrden {
            get {
                return this.numeroOrdenField;
            }
            set {
                this.numeroOrdenField = value;
                this.RaisePropertyChanged("numeroOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public sede sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double totalEgresos {
            get {
                return this.totalEgresosField;
            }
            set {
                this.totalEgresosField = value;
                this.RaisePropertyChanged("totalEgresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double totalIngresos {
            get {
                return this.totalIngresosField;
            }
            set {
                this.totalIngresosField = value;
                this.RaisePropertyChanged("totalIngresos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public vehiculo vehiculo {
            get {
                return this.vehiculoField;
            }
            set {
                this.vehiculoField = value;
                this.RaisePropertyChanged("vehiculo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string correoField;
        
        private int idField;
        
        private string nombreField;
        
        private string numDocumentoField;
        
        private string telefonoField;
        
        private string tipoClienteField;
        
        private string tipoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string numDocumento {
            get {
                return this.numDocumentoField;
            }
            set {
                this.numDocumentoField = value;
                this.RaisePropertyChanged("numDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipoCliente {
            get {
                return this.tipoClienteField;
            }
            set {
                this.tipoClienteField = value;
                this.RaisePropertyChanged("tipoCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class vehiculo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string placaField;
        
        private cliente propietarioField;
        
        private string tipoVehiculoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public cliente propietario {
            get {
                return this.propietarioField;
            }
            set {
                this.propietarioField = value;
                this.RaisePropertyChanged("propietario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipoVehiculo {
            get {
                return this.tipoVehiculoField;
            }
            set {
                this.tipoVehiculoField = value;
                this.RaisePropertyChanged("tipoVehiculo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class sede : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string direccionField;
        
        private string distritoField;
        
        private int idField;
        
        private string nombreField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.megaautos.com.pe/")]
    public partial class comprobantePago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idField;
        
        private double montoField;
        
        private string numeroComprobanteField;
        
        private ordenTrabajo ordenTrabajoField;
        
        private string tipoComprobanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("monto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string numeroComprobante {
            get {
                return this.numeroComprobanteField;
            }
            set {
                this.numeroComprobanteField = value;
                this.RaisePropertyChanged("numeroComprobante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ordenTrabajo ordenTrabajo {
            get {
                return this.ordenTrabajoField;
            }
            set {
                this.ordenTrabajoField = value;
                this.RaisePropertyChanged("ordenTrabajo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
                this.RaisePropertyChanged("tipoComprobante");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCuentaContable", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class actualizarCuentaContableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioCuentaContable.cuentaContable objCC;
        
        public actualizarCuentaContableRequest() {
        }
        
        public actualizarCuentaContableRequest(LP2MegaAutos.ServicioCuentaContable.cuentaContable objCC) {
            this.objCC = objCC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCuentaContableResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class actualizarCuentaContableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarCuentaContableResponse() {
        }
        
        public actualizarCuentaContableResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCuentaContable", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class insertarCuentaContableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioCuentaContable.cuentaContable objCC;
        
        public insertarCuentaContableRequest() {
        }
        
        public insertarCuentaContableRequest(LP2MegaAutos.ServicioCuentaContable.cuentaContable objCC) {
            this.objCC = objCC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCuentaContableResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class insertarCuentaContableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCuentaContableResponse() {
        }
        
        public insertarCuentaContableResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCuentaContable", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class listarCuentaContableRequest {
        
        public listarCuentaContableRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCuentaContableResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class listarCuentaContableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LP2MegaAutos.ServicioCuentaContable.cuentaContable[] @return;
        
        public listarCuentaContableResponse() {
        }
        
        public listarCuentaContableResponse(LP2MegaAutos.ServicioCuentaContable.cuentaContable[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCuentaContable", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class eliminarCuentaContableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCC;
        
        public eliminarCuentaContableRequest() {
        }
        
        public eliminarCuentaContableRequest(int idCC) {
            this.idCC = idCC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCuentaContableResponse", WrapperNamespace="http://services.megaautos.com.pe/", IsWrapped=true)]
    public partial class eliminarCuentaContableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.megaautos.com.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCuentaContableResponse() {
        }
        
        public eliminarCuentaContableResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CuentaContableWSChannel : LP2MegaAutos.ServicioCuentaContable.CuentaContableWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuentaContableWSClient : System.ServiceModel.ClientBase<LP2MegaAutos.ServicioCuentaContable.CuentaContableWS>, LP2MegaAutos.ServicioCuentaContable.CuentaContableWS {
        
        public CuentaContableWSClient() {
        }
        
        public CuentaContableWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuentaContableWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaContableWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuentaContableWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableResponse LP2MegaAutos.ServicioCuentaContable.CuentaContableWS.actualizarCuentaContable(LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableRequest request) {
            return base.Channel.actualizarCuentaContable(request);
        }
        
        public int actualizarCuentaContable(LP2MegaAutos.ServicioCuentaContable.cuentaContable objCC) {
            LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableRequest inValue = new LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableRequest();
            inValue.objCC = objCC;
            LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableResponse retVal = ((LP2MegaAutos.ServicioCuentaContable.CuentaContableWS)(this)).actualizarCuentaContable(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableResponse> LP2MegaAutos.ServicioCuentaContable.CuentaContableWS.actualizarCuentaContableAsync(LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableRequest request) {
            return base.Channel.actualizarCuentaContableAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableResponse> actualizarCuentaContableAsync(LP2MegaAutos.ServicioCuentaContable.cuentaContable objCC) {
            LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableRequest inValue = new LP2MegaAutos.ServicioCuentaContable.actualizarCuentaContableRequest();
            inValue.objCC = objCC;
            return ((LP2MegaAutos.ServicioCuentaContable.CuentaContableWS)(this)).actualizarCuentaContableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableResponse LP2MegaAutos.ServicioCuentaContable.CuentaContableWS.insertarCuentaContable(LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableRequest request) {
            return base.Channel.insertarCuentaContable(request);
        }
        
        public int insertarCuentaContable(LP2MegaAutos.ServicioCuentaContable.cuentaContable objCC) {
            LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableRequest inValue = new LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableRequest();
            inValue.objCC = objCC;
            LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableResponse retVal = ((LP2MegaAutos.ServicioCuentaContable.CuentaContableWS)(this)).insertarCuentaContable(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableResponse> LP2MegaAutos.ServicioCuentaContable.CuentaContableWS.insertarCuentaContableAsync(LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableRequest request) {
            return base.Channel.insertarCuentaContableAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableResponse> insertarCuentaContableAsync(LP2MegaAutos.ServicioCuentaContable.cuentaContable objCC) {
            LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableRequest inValue = new LP2MegaAutos.ServicioCuentaContable.insertarCuentaContableRequest();
            inValue.objCC = objCC;
            return ((LP2MegaAutos.ServicioCuentaContable.CuentaContableWS)(this)).insertarCuentaContableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioCuentaContable.listarCuentaContableResponse LP2MegaAutos.ServicioCuentaContable.CuentaContableWS.listarCuentaContable(LP2MegaAutos.ServicioCuentaContable.listarCuentaContableRequest request) {
            return base.Channel.listarCuentaContable(request);
        }
        
        public LP2MegaAutos.ServicioCuentaContable.cuentaContable[] listarCuentaContable() {
            LP2MegaAutos.ServicioCuentaContable.listarCuentaContableRequest inValue = new LP2MegaAutos.ServicioCuentaContable.listarCuentaContableRequest();
            LP2MegaAutos.ServicioCuentaContable.listarCuentaContableResponse retVal = ((LP2MegaAutos.ServicioCuentaContable.CuentaContableWS)(this)).listarCuentaContable(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioCuentaContable.listarCuentaContableResponse> LP2MegaAutos.ServicioCuentaContable.CuentaContableWS.listarCuentaContableAsync(LP2MegaAutos.ServicioCuentaContable.listarCuentaContableRequest request) {
            return base.Channel.listarCuentaContableAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioCuentaContable.listarCuentaContableResponse> listarCuentaContableAsync() {
            LP2MegaAutos.ServicioCuentaContable.listarCuentaContableRequest inValue = new LP2MegaAutos.ServicioCuentaContable.listarCuentaContableRequest();
            return ((LP2MegaAutos.ServicioCuentaContable.CuentaContableWS)(this)).listarCuentaContableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableResponse LP2MegaAutos.ServicioCuentaContable.CuentaContableWS.eliminarCuentaContable(LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableRequest request) {
            return base.Channel.eliminarCuentaContable(request);
        }
        
        public int eliminarCuentaContable(int idCC) {
            LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableRequest inValue = new LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableRequest();
            inValue.idCC = idCC;
            LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableResponse retVal = ((LP2MegaAutos.ServicioCuentaContable.CuentaContableWS)(this)).eliminarCuentaContable(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableResponse> LP2MegaAutos.ServicioCuentaContable.CuentaContableWS.eliminarCuentaContableAsync(LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableRequest request) {
            return base.Channel.eliminarCuentaContableAsync(request);
        }
        
        public System.Threading.Tasks.Task<LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableResponse> eliminarCuentaContableAsync(int idCC) {
            LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableRequest inValue = new LP2MegaAutos.ServicioCuentaContable.eliminarCuentaContableRequest();
            inValue.idCC = idCC;
            return ((LP2MegaAutos.ServicioCuentaContable.CuentaContableWS)(this)).eliminarCuentaContableAsync(inValue);
        }
    }
}
